# Generated by Django 2.2 on 2019-05-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('addresse', models.CharField(max_length=64)),
                ('code_postal', models.CharField(max_length=8)),
                ('ville', models.CharField(max_length=32)),
                ('pays', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_portable', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('P', 'Partenaire'), ('F', 'Fournisseur'), ('A', 'Abonné'), ('B', 'Bénévole')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Adherent'), ('M', 'Membre'), ('D', 'Donateur')], default='F', max_length=1)),
                ('status', models.CharField(max_length=20)),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('prix', models.IntegerField()),
                ('mode_livraison', models.CharField(max_length=20)),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sous_type', models.CharField(choices=[('A', 'Adherent'), ('M', 'Membre'), ('D', 'Donateur')], default='A', max_length=1)),
                ('date_naissance', models.CharField(max_length=20)),
                ('rgpd', models.IntegerField()),
                ('date_questionnaire', models.CharField(max_length=20)),
                ('message_questionnaire', models.CharField(max_length=64)),
                ('reunion_information', models.CharField(max_length=20)),
                ('formation_communication', models.CharField(max_length=20)),
                ('formation_logicielle', models.CharField(max_length=20)),
                ('formation_distribution', models.CharField(max_length=20)),
                ('niveau_implication', models.IntegerField()),
                ('commentaires', models.CharField(max_length=64)),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('AOC', models.IntegerField()),
                ('AOP', models.IntegerField()),
                ('BIO', models.IntegerField()),
                ('N_and_P', models.IntegerField()),
                ('demeter', models.IntegerField()),
                ('label_rouge', models.IntegerField()),
                ('fair_trade', models.IntegerField()),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.Fournisseur')),
            ],
        ),
    ]
